build: false
shallow_clone: true
platform:
  - x86
  - x64
  - Any CPU
cache:
  - c:\tools\php -> appveyor.yml
init:
  - SET PATH=c:\tools\php;%PATH%
  - SET PHP=1
  - SET COMPOSER_NO_INTERACTION=1
install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - IF %PHP%==1 cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  - IF %PHP%==1 cinst -y php
  - IF %PHP%==1 cd c:\tools\php
  - IF %PHP%==1 copy php.ini-production php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar global require "fxp/composer-asset-plugin:1.2.0"
  - php composer.phar update --prefer-dist
before_test:
  - git --version
  - php --version
test_script:
  - php vendor/bin/phpunit
